### ISSUE TITLE
eedi2cuda.Enlarge2 -> eedi2cuda.Enlarge2pow

### ISSUE THREAD

**Issue by Selur** [AmusementClub/VapourSynth-EEDI2CUDA#1]
would be nice if one could have not just a x2 but also a x4, x8, ... optimized function ;)

**Comment by misakikasumi** [comment]
EEDI2 is originally a field doubling filter. You can find the [original description](http://avisynth.nl/index.php/EEDI2):
> EEDI2 (Enhanced Edge Directed Interpolation) resizes an image by 2x in the vertical direction by copying the existing image to 2*y(n) and interpolating the missing field. It is intended for edge-directed interpolation for deinterlacing (i.e. not really made for resizing a normal image, but can do that as well).

That means, what EEDI2 can do is just doubling the height of the original image.
In the README, I wrote the equivalent of Enlarge2:
```python3
el = core.eedi2cuda.EEDI2(clip, 1)
el = core.fmtc.resample(el, sy=[-.5, -.5 * (1 << clip.format.subsampling_h)])
el = core.std.Transpose(el)
el = core.eedi2cuda.EEDI2(el, 1)
el = core.fmtc.resample(el, sy=[-.5, -.5 * (1 << clip.format.subsampling_w)])
el = core.std.Transpose(el)
```

In fact, Enlarge2 is right implemented in the [similar way](https://github.com/AmusementClub/VapourSynth-EEDI2CUDA/blob/04de969f79528dffe6fa2944540807594a6c9b91/EEDI2.cu#L376):
```
EEDI2Pass
TransposePass
ShiftWPass
EEDI2Pass
TransposePass
ShiftWPass
```

Enlarge2 will still do two passes of EEDI2. Compared with the equivalent that uses CPU-side shifting and transposing, it's faster because all passes are done on the GPU and no unnecessary CPU-GPU memcpy is performed, not because the EEDI2 itself is optimized.
We can calculate the speed up for implementing Enlarge2pow easily. Consider we are enlarge a 540p YUV420P16 image to 4K. On a PCIe 3.0 x16 connected GPU, the typical speed of memcpy between CPU and GPU is around 12GB/s. With two passes of Enlarge2, the intermediate 1080p image will be downloaded to CPU and uploaded to GPU again. This will cost:
```
4096bytes (pitch) * 1080 (height) * 1.5 (planes) / 12GB/s * 2 = 1.03ms
```
I don't think saving the 1ms will make a difference, considering the computation is more time-costing. And, if `num_streams>1`, during the memcpy, other streams can do computation, so the memcpy time is hidden.

EEDI2 is an old filter. It is originally developed by Kevin Stone in 2005-2006. It performs well on SD and HD input, but I doubt whether it's good for UHD input. (If you give it UHD input, you may also need to increase the values of `estr`, `dstr`, and `maxd`. But I'm not sure about this. I have not used EEDI2 on UHD input before.) So I doubt whether Enlarge2pow is useful. If you enlarge 1080p to 8K, I won't suggest using EEDI2 in the 2K to 4K step. If you enlarge 540p to 4K, I won't suggest using EEDI2 in the 540p to 1080p step, because 540p is typically a DVD source. DVDs usually contains a lot of encoding artefacts that EEDI2 might not be good at dealing with. You may be interested in Waifu2x or Anime4K for anime DVDs.
BTW, here is an advertisement. @AkarinVS recently developed a [DLVFX filter](https://github.com/AkarinVS/vapoursynth-plugin/releases/tag/v0.70). I found its artefact reduction is powerful. If you're dealing with bad DVD sources or Web sources, you may be interested about it.
